	#include "/Engine/Public/Platform.ush"
 
Buffer<float3> Input;
RWBuffer<float> Output;
 
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void XVLODSelectorShader(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex )
{
	float3 vec1 = Input[0];
	float3 vec2 = Input[1];
	// Calculate the squared distance
	float distance = length(vec1 - vec2);
	// Output the distance (square root of the squared distance)
	Output[0] = sqrt(distance);
}